---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finala.fullname" . }}-elasticsearch-config
  labels:
    chart: "{{ .Chart.Name }}"
    app: "{{ include "finala.fullname" . }}-elasticsearch"
data:
{{- range $path, $config := .Values.storage.esConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}