{{- if (eq .Values.storage.type "internal") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
{{ include "finala.labels" . | indent 4 }}
    component: {{ include "finala.fullname" . }}-elasticsearch
spec:
  selector:
    matchLabels:
      component: {{ include "finala.fullname" . }}-elasticsearch
  template:
    metadata:
      labels:
        component: {{ include "finala.fullname" . }}-elasticsearch
    spec:
      volumes:
        - name: esconfig
          configMap:
            name: {{ include "finala.fullname" . }}-elasticsearch-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: NodeType
                    operator: In
                    values:
                      - gitops
      tolerations:
        - key: "gitops"
          value: "true"
          effect: "NoSchedule"
      containers:
      - name: {{ include "finala.fullname" . }}-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        {{- range $path, $config := .Values.storage.esConfig }}
        - name: esconfig
          mountPath: /usr/share/elasticsearch/config/{{ $path }}
          subPath: {{ $path }}
        {{- end -}}
{{- end }}