name: Go
on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: curl -L "https://app.spectralops.io/latest/sh?dsn=$SPECTRAL_DSN" | sudo sh
      - name: Scan
        run: spectral scan
